In [1]:
import Pkg
Pkg.update()
Pkg.add("LinearAlgebra")

    Updating registry at `~/.julia/registries/General`
   Installed InlineStrings ────── v1.1.1
   Installed Glib_jll ─────────── v2.68.3+2
   Installed Cairo_jll ────────── v1.16.1+1
   Installed NaNMath ──────────── v0.3.6
   Installed Parsers ──────────── v2.1.3
   Installed Tables ───────────── v1.6.1
   Installed Distributions ────── v0.25.36
   Installed PlotUtils ────────── v1.1.1
   Installed Requires ─────────── v1.2.0
   Installed LogExpFunctions ──── v0.3.6
   Installed Compat ───────────── v3.41.0
   Installed SpecialFunctions ─── v2.0.0
   Installed DataStructures ───── v0.18.11
   Installed ChangesOfVariables ─ v0.1.2
   Installed Interpolations ───── v0.13.5
   Installed Plots ────────────── v1.25.2
    Updating `~/.julia/environments/v1.6/Project.toml`
  [91a5bcdd] ↑ Plots v1.25.1 ⇒ v1.25.2
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [9e997f8a] ↑ ChangesOfVariables v0.1.1 ⇒ v0.1.2
  [34da2185] ↑ Compat v3.40.0 ⇒ v3.41.0
  [864edb3b] ↑ DataStructures v0.18.

In [2]:
using LinearAlgebra

In [3]:
Pkg.add("Statistics")
using Statistics

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.6/Project.toml`
  No Changes to `~/.julia/environments/v1.6/Manifest.toml`
Precompiling project...
  ✓ Conda
  ✓ InlineStrings
  ✓ IJulia
  ✓ TimeZones
  ✓ PyCall
  ✓ Intervals
  ✓ Polynomials
  ✓ DSP
  ✓ Plots
  9 dependencies successfully precompiled in 35 seconds (164 already precompiled)
  2 dependencies precompiled but different versions are currently loaded. Restart julia to access the new versions


In [4]:
include("iris_flower_data.jl")
include("iris_multiclass_helpers.jl")

confusion_matrix (generic function with 1 method)

In [5]:
X_t = transpose(X)

X_train = X_t[1:100, 1:4]

Y_train = y[1:100]

X_test = X_t[101: 150, 1:4]

Y_test = y[101:150]

50-element Vector{Float64}:
 2.0
 3.0
 2.0
 2.0
 1.0
 1.0
 3.0
 3.0
 3.0
 2.0
 1.0
 1.0
 3.0
 ⋮
 1.0
 2.0
 1.0
 2.0
 2.0
 1.0
 3.0
 1.0
 2.0
 1.0
 2.0
 1.0

In [6]:
setosa_trainY = zeros(100)
for i in 1:100
    if Y_train[i] == 1
        setosa_trainY[i] = 1
    else
        setosa_trainY[i] = -1
    end
end

setosa_testY = zeros(50)
for i in 1:50
    if Y_test[i] == 1
        setosa_testY[i] = 1
    else
        setosa_testY[i] = -1
    end
end

setosa = X_train\setosa_trainY

function setosa_func(x)
    f = x[1]*setosa[1] + x[2]*setosa[2] + x[3]*setosa[3] + x[4]*setosa[4]
    if f >= 0
        return 1.0
    else
        return -1.0
    end
end

setosa_func (generic function with 1 method)

In [7]:
correct_training = 0
correct_test = 0

for i in 1:50
    if setosa_func(X_test[i, 1:4]) - Y_test[i] <= 0.01
        correct_test += 1
    end
   
end

for i in 1:100
    if setosa_func(X_train[i, 1:4]) - Y_train[i] <= 0.01
        correct_training += 1
    end
   
end

print("Setosa Training Accuracy: ", (correct_training / 100) * 100, " ")
print("Setosa Test Accuracy: ", (correct_test / 50) * 100)

Setosa Training Accuracy: 100.0 Setosa Test Accuracy: 100.0

In [8]:

versicolor_trainY = zeros(100)
for i in 1:100
    if Y_train[i] == 2
        versicolor_trainY[i] = 1
    else
        versicolor_trainY[i] = -1
    end
end

versicolor_testY = zeros(50)
for i in 1:50
    if Y_train[i] == 2
        versicolor_testY[i] = 1
    else
        versicolor_testY[i] = -1
    end
end

versicolor = X_train\versicolor_trainY

4-element Vector{Float64}:
  0.44213815089788006
 -0.8538243912967147
  0.13418476023699685
 -0.7048174071960329

In [9]:
function versicolor_func(x)
    f = x[1]*versicolor[1] + x[2]*versicolor[2] + x[3]*versicolor[3] + x[4]*versicolor[4]
    if f >= 0
        return 1.0
    else
        return -1.0
    end
end

correct_training = 0
correct_test = 0

for i in 1:50
    if versicolor_func(X_test[i, 1:4]) - Y_test[i] <= 0.01
        correct_test += 1
    end
   
end

for i in 1:100
    if versicolor_func(X_train[i, 1:4]) - Y_train[i] <= 0.01
        correct_training += 1
    end
   
end

print("Versicolor Training Accuracy: ", (correct_training / 100) * 100, " ")
print("Versicolor Test Accuracy: ", (correct_test / 50) * 100)

Versicolor Training Accuracy: 100.0 Versicolor Test Accuracy: 100.0

In [10]:
virginica_trainY = zeros(100)
for i in 1:100
    if Y_train[i] == 3
        virginica_trainY[i] = 1
    else
        virginica_trainY[i] = -1
    end
end

virginica_testY = zeros(50)
for i in 1:50
    if Y_train[i] == 3
        virginica_testY[i] = 1
    else
        virginica_testY[i] = -1
    end
end

virginica = X_train\virginica_trainY

4-element Vector{Float64}:
 -0.534378082352365
  0.2834329969066022
  0.20299034121861312
  1.0001763685229135

In [11]:
function virginica_func(x)
    f = x[1]*virginica[1] + x[2]*virginica[2] + x[3]*virginica[3] + x[4]*virginica[4]
    if f >= 0
        return 1.0
    else
        return -1.0
    end
end

correct_training = 0
correct_test = 0

for i in 1:50
    if virginica_func(X_test[i, 1:4]) - Y_test[i] <= 0.01
        correct_test += 1
    end
   
end

for i in 1:100
    if virginica_func(X_train[i, 1:4]) - Y_train[i] <= 0.01
        correct_training += 1
    end
   
end

print("Versicolor Training Accuracy: ", (correct_training / 100) * 100, " ")
print("Virginica Accuracy Test Accuracy: ", (correct_test / 50) * 100)

Versicolor Training Accuracy: 100.0 Virginica Accuracy Test Accuracy: 100.0

In [12]:
solution = X_train \Y_train
function classifier(x)
    s = solution[1]*x[1] + solution[2]*x[2] + solution[3]*x[3] + solution[4]*x[4]
    return round(s)
end

yHat = round.(X_t * solution)

150-element Vector{Float64}:
 1.0
 1.0
 3.0
 2.0
 1.0
 2.0
 1.0
 3.0
 2.0
 3.0
 1.0
 1.0
 1.0
 ⋮
 1.0
 2.0
 1.0
 2.0
 2.0
 1.0
 3.0
 1.0
 2.0
 1.0
 2.0
 1.0

In [13]:
c_matrix = confusion_matrix(yHat, y)
print(c_matrix)

[50.0 0.0 0.0; 0.0 47.0 3.0; 0.0 3.0 47.0]